"""Version information for depkeeper.

This module provides the single source of truth for depkeeper's version
number and related metadata. It follows Semantic Versioning 2.0.0 as
specified at https://semver.org/

The version string is automatically parsed into structured components,
making it easy to perform version comparisons and feature detection
based on the current version.

Version Format
--------------
Semantic Versioning format:

    MAJOR.MINOR.PATCH[-PRERELEASE][+BUILD]

Where:

- **MAJOR**: Incompatible API changes
- **MINOR**: Backwards-compatible functionality additions
- **PATCH**: Backwards-compatible bug fixes
- **PRERELEASE**: Optional pre-release identifier (dev, alpha, beta, rc)
- **BUILD**: Optional build metadata (not used in depkeeper)

Examples
--------
Valid version strings:

    >>> __version__ = "0.1.0"          # Development release
    >>> __version__ = "0.1.0.dev0"     # Pre-release (dev)
    >>> __version__ = "1.0.0-alpha1"   # Alpha release
    >>> __version__ = "1.0.0-beta2"    # Beta release
    >>> __version__ = "1.0.0-rc1"      # Release candidate
    >>> __version__ = "1.2.3"          # Stable release

Accessing version information:

    >>> from depkeeper import __version__
    >>> print(__version__)
    0.1.0.dev0

    >>> from depkeeper.__version__ import VERSION_INFO
    >>> print(VERSION_INFO["major"])
    0
    >>> print(VERSION_INFO["is_dev"])
    True

    >>> from depkeeper.__version__ import VERSION_STRING
    >>> print(VERSION_STRING)
    depkeeper 0.1.0.dev0

Pre-release Identifiers
-----------------------
Pre-release versions are indicated by a hyphen or dot followed by an
identifier:

- **dev**: Development/nightly builds (e.g., 0.1.0.dev0, 0.1.0.dev1)
- **alpha/a**: Alpha releases (e.g., 1.0.0-alpha1)
- **beta/b**: Beta releases (e.g., 1.0.0-beta1)
- **rc**: Release candidates (e.g., 1.0.0-rc1)

Development versions (dev) are considered less stable than any other
identifier and should not be used in production.

Notes
-----
This module should be the only place where the version is defined.
All other modules should import from here:

    >>> from depkeeper.__version__ import __version__

The VERSION_INFO dictionary is automatically generated by parsing
__version__ and should not be modified directly.

Version comparison should be done using the packaging library:

    >>> from packaging.version import Version
    >>> from depkeeper import __version__
    >>> if Version(__version__) >= Version("1.0.0"):
    ...     print("Stable release")

See Also
--------
packaging.version : PEP 440 compliant version parsing
https://semver.org/ : Semantic Versioning specification
https://peps.python.org/pep-0440/ : Python version identification
"""

from __future__ import annotations

import re
from typing import Any, Dict

# ---------------------------------------------------------------------------
# Main version (single source of truth)
# ---------------------------------------------------------------------------

__version__ = "0.1.0.dev0"


# ---------------------------------------------------------------------------
# Structured version metadata
# ---------------------------------------------------------------------------


def _parse_version(version: str) -> Dict[str, Any]:
    """Parse a semantic version string into structured components.

    Internal helper function that breaks down a version string following
    Semantic Versioning into its constituent parts. This enables programmatic
    access to version components without manual string parsing.

    The function supports both hyphen and dot separators for pre-release
    identifiers (e.g., "1.0.0-dev0" and "1.0.0.dev0" are both valid).

    Parameters
    ----------
    version : str
        The version string to parse. Must follow the format:
        MAJOR.MINOR.PATCH[-PRERELEASE] or MAJOR.MINOR.PATCH.PRERELEASE

        Examples:
        - "0.1.0"
        - "0.1.0.dev0"
        - "1.0.0-rc1"
        - "2.3.5-beta2"

    Returns
    -------
    dict
        A dictionary containing the parsed version components:

        - **major** (int): Major version number
        - **minor** (int): Minor version number
        - **patch** (int): Patch version number
        - **prerelease** (str | None): Pre-release identifier if present,
          None otherwise
        - **is_dev** (bool): True if this is a development version (pre-release
          starts with 'dev'), False otherwise

    Raises
    ------
    ValueError
        If the version string does not match the expected format or contains
        invalid characters.

    Examples
    --------
    Parse a stable release version:

        >>> _parse_version("1.2.3")
        {'major': 1, 'minor': 2, 'patch': 3, 'prerelease': None, 'is_dev': False}

    Parse a development version:

        >>> _parse_version("0.1.0.dev0")
        {'major': 0, 'minor': 1, 'patch': 0, 'prerelease': 'dev0', 'is_dev': True}

    Parse a release candidate:

        >>> _parse_version("1.0.0-rc1")
        {'major': 1, 'minor': 0, 'patch': 0, 'prerelease': 'rc1', 'is_dev': False}

    Invalid version raises ValueError:

        >>> _parse_version("invalid")
        Traceback (most recent call last):
            ...
        ValueError: Invalid version string: invalid

    Notes
    -----
    This function is internal and not part of the public API. It's called
    automatically when the module is imported to populate VERSION_INFO.

    The function does not validate semantic versioning rules beyond basic
    format checking. For full PEP 440 compliance, use the packaging library:

        >>> from packaging.version import Version
        >>> Version(__version__)  # Raises InvalidVersion if malformed

    See Also
    --------
    packaging.version.Version : PEP 440 compliant version parsing
    """
    pattern = r"^(\d+)\.(\d+)\.(\d+)(?:[.-]([a-zA-Z0-9]+))?$"
    match = re.match(pattern, version)

    if not match:
        error_message = f"Invalid version string: {version}"
        raise ValueError(error_message)

    major, minor, patch, pre = match.groups()

    return {
        "major": int(major),
        "minor": int(minor),
        "patch": int(patch),
        "prerelease": pre,
        "is_dev": pre is not None and pre.startswith("dev"),
    }


# Automatically parse version on module import
VERSION_INFO = _parse_version(__version__)
"""Structured version information dictionary.

Automatically generated by parsing __version__ when the module is imported.
Contains major, minor, patch, prerelease, and is_dev fields.

Examples
--------
    >>> from depkeeper.__version__ import VERSION_INFO
    >>> print(f"Major version: {VERSION_INFO['major']}")
    Major version: 0
    >>> if VERSION_INFO['is_dev']:
    ...     print("Development version detected")
    Development version detected
"""


# ---------------------------------------------------------------------------
# Human-readable version (for CLI)
# ---------------------------------------------------------------------------

VERSION_STRING = f"depkeeper {__version__}"
"""Human-readable version string for display in CLI output.

Combines the package name with the version number for user-facing output.
Used in --version flag output and help messages.

Examples
--------
    >>> from depkeeper.__version__ import VERSION_STRING
    >>> print(VERSION_STRING)
    depkeeper 0.1.0.dev0
"""
